# AI Dependency Manager - Production Configuration
# This file contains production-specific settings for the AI Dependency Manager

# Database configuration
database:
  path: "/data/ai-dep-manager-prod.db"
  max_connections: 25
  connection_timeout: 30s
  backup_interval: "24h"

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "/app/logs/ai-dep-manager.log"
  max_size: 100  # MB
  max_files: 10
  max_age: 30    # days
  compress: true
  
  # Structured logging fields
  include_caller: false
  include_timestamp: true
  include_level: true
  include_request_id: true

# Web server configuration
server:
  host: "0.0.0.0"
  port: 8080
  api_port: 8081
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  max_header_bytes: 1048576  # 1MB

# API configuration
api:
  rate_limit: 100  # requests per minute
  cors_origins: ["*"]
  cors_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  cors_headers: ["*"]
  enable_swagger: false  # Disable in production

# Security configuration
security:
  enable_https: false  # Set to true with proper certificates
  cert_file: ""
  key_file: ""
  secure_headers: true
  content_security_policy: "default-src 'self'"

# Performance configuration
performance:
  max_concurrent_scans: 10
  scan_timeout: "10m"
  cache_ttl: "1h"
  gc_percent: 80

# Notification configuration
notifications:
  enabled: true
  channels:
    - type: "webhook"
      url: "https://your-webhook-url.com/notifications"
      timeout: "10s"
    - type: "console"
      enabled: true

# Package manager configurations
package_managers:
  npm:
    enabled: true
    registry_url: "https://registry.npmjs.org"
    timeout: "30s"
  
  pip:
    enabled: true
    index_url: "https://pypi.org/simple"
    timeout: "30s"
  
  maven:
    enabled: true
    central_url: "https://repo1.maven.org/maven2"
    timeout: "30s"
  
  gradle:
    enabled: true
    timeout: "30s"

# AI analysis configuration
ai:
  enabled: true
  provider: "openai"  # or "anthropic", "local"
  model: "gpt-3.5-turbo"
  max_tokens: 1000
  temperature: 0.1
  timeout: "30s"

# Monitoring configuration
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_interval: "30s"
  profiling_enabled: false  # Disable in production
